[package]
name = "rs-echo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.5.10", features=["derive"]}
nix = { path="nix" , features=["socket", "net", "uio"]}
slog = "2.7.0"
slog-term = "2.9.1"
