[package]
name = "diagnose"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
bleecn = { path="bleecn/bleecn" }
slog = "2.7.0"
slog-stream = "1.2.1"
slog-json = "2.6.1"
slog-term = "2.9.1"
serde_json = "1.0.120"
maxminddb = "0.24.0"
serde = "1.0.204"
